pipeline:
  class_path: src.pipeline.DynamicPipeline
  init_args:
    do_ica: False
    line_freqs: [60]
    sfreq: 200 #resampling freq
    quality_check: False # wont remove timepoints
    lp_freq: 75 # QA_lp_freq. used during QA: need to preprocess the data a bit -> then do QA
    hp_freq: 0.1 # QA_hp_freq
    preproc_lp_freq: "same" # used during preprocessing
    preproc_hp_freq: "same" # used during preprocessing
    keep_remainder: True
    run_ransac: False
    run_drop_bad_channels: False
    run_detrend: False
    preproc_line_noise_option: None # we can tune this setting? 'mnenotch', None, or default
    preproc_line_freqs: [] #notch filter: apply for every single data pt (data need to be obtained from 60 powergrid)
    rereference_option: 'ar' #can do 'ar', 'le', or None
    missing_chs_option: ignore # can do 'interpolate', 'zero', 'remove', or 'ignore'
    # TODO: turn off bad channel detection by an option
    drop_extra_chs: False # means to drop by TUEG's specific setting, need to turn off for moabb data
    reorder_chs: False # do this operation in post-processing part
    resample_method: 'default' #can do 'resample', 'mne','decimate', None, ...
dataset_path: /home/mila/q/qingchen.hu/LincLab_LaBraM/mne_data/MNE-eegbci-data
out_path: /home/mila/q/qingchen.hu/SPEED_MILA/preprocessing_results/out
log_path: /home/mila/q/qingchen.hu/SPEED_MILA/preprocessing_results/log2.txt
overwrite: False
shuffle_files: True
batch_size: 1 #! if this is not 1, then each one HDF != one EDF!! 주의!! 
n_jobs: 1 #! for testing  #! can be set to larger if wanted!
save_method: 'tueg_fif_ours' #can do "tueg_fif_ours", "default", #"h5_ours"
